// Auto-generated by parallel_unsplash_photos_search
// Do not edit manually

export const IMAGES = {
  CIRCUIT_BG_1: "https://images.unsplash.com/photo-1597173791855-eb1382acd788?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwxfHxjaXJjdWl0JTIwYm9hcmQlMjB0ZWNobm9sb2d5JTIwYmFja2dyb3VuZHxlbnwwfDB8fHRlYWx8MTc3MDgyMTg4Mnww&ixlib=rb-4.1.0&q=80&w=1080",
  CIRCUIT_BG_2: "https://images.unsplash.com/photo-1656337426914-5e5ba162d606?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwyfHxjaXJjdWl0JTIwYm9hcmQlMjB0ZWNobm9sb2d5JTIwYmFja2dyb3VuZHxlbnwwfDB8fHRlYWx8MTc3MDgyMTg4Mnww&ixlib=rb-4.1.0&q=80&w=1080",
  CYBERPUNK_TERMINAL_1: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwxMHx8Y3liZXJwdW5rJTIwbmVvbiUyMHRlcm1pbmFsJTIwY29tcHV0ZXIlMjBzY3JlZW58ZW58MHwwfHxibHVlfDE3NzA4MjE4ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  CYBERPUNK_TERMINAL_10: "https://images.unsplash.com/photo-1665211097563-163d6be45d67?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw5fHxjeWJlcnB1bmslMjBuZW9uJTIwdGVybWluYWwlMjBjb21wdXRlciUyMHNjcmVlbnxlbnwwfDB8fGJsdWV8MTc3MDgyMTg4Mnww&ixlib=rb-4.1.0&q=80&w=1080",
  CYBERPUNK_TERMINAL_2: "https://images.unsplash.com/photo-1591439657848-9f4b9ce436b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw4fHxjeWJlcnB1bmslMjBuZW9uJTIwdGVybWluYWwlMjBjb21wdXRlciUyMHNjcmVlbnxlbnwwfDB8fGJsdWV8MTc3MDgyMTg4Mnww&ixlib=rb-4.1.0&q=80&w=1080",
  CYBERPUNK_TERMINAL_3: "https://images.unsplash.com/photo-1660644808219-1f103401bc85?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwxfHxjeWJlcnB1bmslMjBuZW9uJTIwdGVybWluYWwlMjBjb21wdXRlciUyMHNjcmVlbnxlbnwwfDB8fGJsdWV8MTc3MDgyMTg4Mnww&ixlib=rb-4.1.0&q=80&w=1080",
  CYBERPUNK_TERMINAL_4: "https://images.unsplash.com/photo-1589523322065-40163a8dd001?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw0fHxjeWJlcnB1bmslMjBuZW9uJTIwdGVybWluYWwlMjBjb21wdXRlciUyMHNjcmVlbnxlbnwwfDB8fGJsdWV8MTc3MDgyMTg4Mnww&ixlib=rb-4.1.0&q=80&w=1080",
  CYBERPUNK_TERMINAL_5: "https://images.unsplash.com/photo-1599758783732-bc41592719c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw1fHxjeWJlcnB1bmslMjBuZW9uJTIwdGVybWluYWwlMjBjb21wdXRlciUyMHNjcmVlbnxlbnwwfDB8fGJsdWV8MTc3MDgyMTg4Mnww&ixlib=rb-4.1.0&q=80&w=1080",
  CYBERPUNK_TERMINAL_6: "https://images.unsplash.com/photo-1603671964566-5a344a672c66?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwzfHxjeWJlcnB1bmslMjBuZW9uJTIwdGVybWluYWwlMjBjb21wdXRlciUyMHNjcmVlbnxlbnwwfDB8fGJsdWV8MTc3MDgyMTg4Mnww&ixlib=rb-4.1.0&q=80&w=1080",
  CYBERPUNK_TERMINAL_7: "https://images.unsplash.com/photo-1618849821300-5f216d5e4937?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw2fHxjeWJlcnB1bmslMjBuZW9uJTIwdGVybWluYWwlMjBjb21wdXRlciUyMHNjcmVlbnxlbnwwfDB8fGJsdWV8MTc3MDgyMTg4Mnww&ixlib=rb-4.1.0&q=80&w=1080",
  CYBERPUNK_TERMINAL_8: "https://images.unsplash.com/photo-1698322748750-b5d242c5e43b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw3fHxjeWJlcnB1bmslMjBuZW9uJTIwdGVybWluYWwlMjBjb21wdXRlciUyMHNjcmVlbnxlbnwwfDB8fGJsdWV8MTc3MDgyMTg4Mnww&ixlib=rb-4.1.0&q=80&w=1080",
  CYBERPUNK_TERMINAL_9: "https://images.unsplash.com/photo-1660144425546-b07680e711d1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwyfHxjeWJlcnB1bmslMjBuZW9uJTIwdGVybWluYWwlMjBjb21wdXRlciUyMHNjcmVlbnxlbnwwfDB8fGJsdWV8MTc3MDgyMTg4Mnww&ixlib=rb-4.1.0&q=80&w=1080",
} as const;

export type ImageKey = keyof typeof IMAGES;
